data_params:
    data_path: '../dataset/basic/'
    log_path: './save/log/'
    n_classes: 7
train_params:
    batch_size: 32
    num_workers: 2
    num_epochs: 50
    lr: 0.0001
    gpu_id: 0
    checkpoint_path: './save/checkpoint/'